version: '2'
services:
  registry:
    restart: always
    build: .
    container_name: "registry"
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_USER: registry-user
      REGISTRY_PASSWORD: TESTPASWWORD123456#{
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /var/lib/docker/registry:/var/lib/registry
      - ./certs:/certs
